//! AGENTS.md validation scanner — validates the binding-contract
//! structure of `AGENTS.md`, `CLAUDE.md`, and `AGENT.md` files. Enforces
//! five rules:
//!
//! 1. **usage-protocol** — the file should contain a "Usage Protocol"
//!    section describing the binding-contract nature (info).
//! 2. **jit-index** — the file should contain a "JIT Index" or similar
//!    table of contents for quick navigation (info).
//! 3. **no-absolute-paths** — the file must not contain absolute
//!    filesystem paths (`/Users/...`, `/home/...`) (warning).
//! 4. **no-ai-attribution** — the file must not contain AI tool
//!    attribution boilerplate ("Generated by", "Co-Authored-By: Devin")
//!    (error).
//! 5. **child-chain** — if the file references child `AGENTS.md` files,
//!    those files should exist (warning).
//!
//! This scanner is distinct from `markdown_frontmatter.rs`, which
//! validates generic `.md` YAML frontmatter (title/synopsis/tags). This
//! scanner targets only the special agent-contract filenames and checks
//! body structure, not frontmatter.

use crate::scanners::ScannerIssue;
use crate::utils::{build_exclusions, is_excluded_rel, walk_project, Result};
use std::path::Path;
use tracing::debug;

/// Filenames treated as agent-contract files (case-sensitive).
const AGENT_FILE_NAMES: &[&str] = &["AGENTS.md", "CLAUDE.md", "AGENT.md"];

/// Default AI-attribution patterns flagged by the `no-ai-attribution` rule.
pub const DEFAULT_AI_ATTRIBUTION_PATTERNS: &[&str] = &[
    "Generated with [Devin]",
    "Co-Authored-By: Devin",
    "Generated by AI",
    "Generated by Devin",
];

pub struct AgentsMdScanner {
    require_usage_protocol: bool,
    require_jit_index: bool,
    check_child_chain: bool,
    attribution_patterns: Vec<String>,
    excluded: Vec<String>,
}

impl AgentsMdScanner {
    pub fn new() -> Self {
        Self {
            require_usage_protocol: false,
            require_jit_index: false,
            check_child_chain: true,
            attribution_patterns: DEFAULT_AI_ATTRIBUTION_PATTERNS
                .iter()
                .map(|s| s.to_string())
                .collect(),
            excluded: build_exclusions(&[], false),
        }
    }

    pub fn with_config(
        require_usage_protocol: bool,
        require_jit_index: bool,
        check_child_chain: bool,
        attribution_patterns: Vec<String>,
    ) -> Self {
        Self {
            require_usage_protocol,
            require_jit_index,
            check_child_chain,
            attribution_patterns,
            excluded: build_exclusions(&[], false),
        }
    }

    pub fn with_exclusions(
        require_usage_protocol: bool,
        require_jit_index: bool,
        check_child_chain: bool,
        attribution_patterns: Vec<String>,
        excluded: Vec<String>,
    ) -> Self {
        Self {
            require_usage_protocol,
            require_jit_index,
            check_child_chain,
            attribution_patterns,
            excluded,
        }
    }

    /// Scan a project root for agent-contract files and validate each.
    pub fn scan(&self, project_path: &str) -> Result<Vec<ScannerIssue>> {
        let root = Path::new(project_path);
        let mut issues = Vec::new();

        for entry in walk_project(root, &self.excluded, 6).filter(|e| e.file_type().is_file()) {
            let path = entry.path();
            let name = path.file_name().unwrap_or_default().to_string_lossy();
            if !AGENT_FILE_NAMES.contains(&name.as_ref()) {
                continue;
            }
            let rel = path
                .strip_prefix(root)
                .unwrap_or(path)
                .to_string_lossy()
                .to_string();
            if is_excluded_rel(&rel, &self.excluded) {
                continue;
            }
            debug!("agents_md: scanning {}", rel);
            issues.extend(self.scan_agent_file(path, &rel, root));
        }

        Ok(issues)
    }

    fn scan_agent_file(&self, path: &Path, rel: &str, root: &Path) -> Vec<ScannerIssue> {
        let mut issues = Vec::new();
        let Ok(content) = std::fs::read_to_string(path) else {
            return issues;
        };
        let lower = content.to_lowercase();

        if self.require_usage_protocol && !has_section(&lower, "usage protocol") {
            issues.push(ScannerIssue::new(
                "agents-md-usage-protocol",
                "info",
                rel,
                "AGENTS.md should contain a \"Usage Protocol\" section describing the binding contract nature",
            ));
        }

        if self.require_jit_index
            && !has_section(&lower, "jit index")
            && !has_section(&lower, "table of contents")
            && !has_section(&lower, "index")
        {
            issues.push(ScannerIssue::new(
                "agents-md-jit-index",
                "info",
                rel,
                "AGENTS.md should contain a \"JIT Index\" or table of contents for quick navigation",
            ));
        }

        for (i, line) in content.lines().enumerate() {
            if has_absolute_home_path(line) {
                issues.push(
                    ScannerIssue::new(
                        "agents-md-no-absolute-paths",
                        "warning",
                        rel,
                        format!("absolute filesystem path found: {}", line.trim()),
                    )
                    .at_line(i + 1),
                );
            }
            for pat in &self.attribution_patterns {
                if line.contains(pat) {
                    issues.push(
                        ScannerIssue::new(
                            "agents-md-no-ai-attribution",
                            "error",
                            rel,
                            format!("AI tool attribution found: {}", pat),
                        )
                        .at_line(i + 1),
                    );
                }
            }
        }

        if self.check_child_chain {
            issues.extend(self.check_child_chain(&content, rel, root));
        }

        issues
    }

    fn check_child_chain(&self, content: &str, rel: &str, root: &Path) -> Vec<ScannerIssue> {
        let mut issues = Vec::new();
        for (i, line) in content.lines().enumerate() {
            for referenced in extract_child_agents_refs(line) {
                let candidate = root.join(&referenced);
                if !candidate.exists() {
                    issues.push(
                        ScannerIssue::new(
                            "agents-md-child-chain",
                            "warning",
                            rel,
                            format!("referenced child agent file does not exist: {}", referenced),
                        )
                        .at_line(i + 1),
                    );
                }
            }
        }
        issues
    }
}

impl Default for AgentsMdScanner {
    fn default() -> Self {
        Self::new()
    }
}

/// Case-insensitive section heading check. A section is a markdown heading
/// (`#`, `##`, ...) whose text contains `needle`.
fn has_section(lowered_content: &str, needle: &str) -> bool {
    for line in lowered_content.lines() {
        let trimmed = line.trim_start();
        if let Some(rest) = trimmed.strip_prefix('#') {
            let rest = rest.trim_start_matches('#').trim();
            if rest.contains(needle) {
                return true;
            }
        }
    }
    false
}

/// Detect absolute home paths: `/Users/<name>/` or `/home/<name>/`.
fn has_absolute_home_path(line: &str) -> bool {
    (line.contains("/Users/") && line.contains("/"))
        || (line.contains("/home/") && line.contains("/"))
}

/// Extract relative paths to child `AGENTS.md` / `CLAUDE.md` / `AGENT.md`
/// files referenced in a line. Recognizes markdown-link `](path)` and
/// bare-path forms (e.g. `./sub/AGENTS.md`).
fn extract_child_agents_refs(line: &str) -> Vec<String> {
    let mut refs = Vec::new();
    for needle in ["AGENTS.md", "CLAUDE.md", "AGENT.md"] {
        let mut start = 0;
        while let Some(idx) = line[start..].find(needle) {
            let abs = start + idx;
            let end = abs + needle.len();
            // Look backwards from `abs` to find the path prefix. In a
            // markdown link `](./sub/AGENTS.md)`, the `(` marks the start
            // of the path. Otherwise, scan backwards for a path-start
            // boundary (whitespace, quote, or start of line).
            let prefix_start = line[..abs]
                .rfind("](")
                .map(|p| p + 2)
                .or_else(|| {
                    let bytes = line[..abs].as_bytes();
                    let mut p = abs;
                    while p > 0 {
                        let b = bytes[p - 1];
                        if b == b'/'
                            || b == b'.'
                            || b == b'_'
                            || b == b'-'
                            || b.is_ascii_alphanumeric()
                        {
                            p -= 1;
                        } else {
                            break;
                        }
                    }
                    if p == abs {
                        None
                    } else {
                        Some(p)
                    }
                })
                .unwrap_or(abs);
            let path_str = &line[prefix_start..end];
            let cleaned = path_str
                .trim_start_matches("./")
                .trim_start_matches("../")
                .to_string();
            if !cleaned.is_empty() && !refs.contains(&cleaned) {
                refs.push(cleaned);
            }
            start = end;
        }
    }
    refs
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn write_agents_md(dir: &Path, body: &str) {
        std::fs::write(dir.join("AGENTS.md"), body).unwrap();
    }

    #[test]
    fn valid_agents_md_no_issues() -> Result<()> {
        let dir = TempDir::new()?;
        write_agents_md(
            dir.path(),
            "# Project Agent Directives\n\nSome guidance here.\n",
        );
        let scanner = AgentsMdScanner::new();
        assert!(scanner.scan(&dir.path().to_string_lossy())?.is_empty());
        Ok(())
    }

    #[test]
    fn flags_missing_usage_protocol_when_required() -> Result<()> {
        let dir = TempDir::new()?;
        write_agents_md(dir.path(), "# Project\n\nGuidance.\n");
        let scanner = AgentsMdScanner::with_config(true, false, true, Vec::new());
        let issues = scanner.scan(&dir.path().to_string_lossy())?;
        assert!(issues
            .iter()
            .any(|i| i.rule == "agents-md-usage-protocol" && i.severity == "info"));
        Ok(())
    }

    #[test]
    fn usage_protocol_present_passes() -> Result<()> {
        let dir = TempDir::new()?;
        write_agents_md(
            dir.path(),
            "# Project\n\n## Usage Protocol\n\nFollow this.\n",
        );
        let scanner = AgentsMdScanner::with_config(true, false, true, Vec::new());
        let issues = scanner.scan(&dir.path().to_string_lossy())?;
        assert!(!issues.iter().any(|i| i.rule == "agents-md-usage-protocol"));
        Ok(())
    }

    #[test]
    fn flags_missing_jit_index_when_required() -> Result<()> {
        let dir = TempDir::new()?;
        write_agents_md(dir.path(), "# Project\n\nGuidance.\n");
        let scanner = AgentsMdScanner::with_config(false, true, true, Vec::new());
        let issues = scanner.scan(&dir.path().to_string_lossy())?;
        assert!(issues
            .iter()
            .any(|i| i.rule == "agents-md-jit-index" && i.severity == "info"));
        Ok(())
    }

    #[test]
    fn jit_index_table_of_contents_passes() -> Result<()> {
        let dir = TempDir::new()?;
        write_agents_md(
            dir.path(),
            "# Project\n\n## Table of Contents\n\n- [Intro](#intro)\n",
        );
        let scanner = AgentsMdScanner::with_config(false, true, true, Vec::new());
        let issues = scanner.scan(&dir.path().to_string_lossy())?;
        assert!(!issues.iter().any(|i| i.rule == "agents-md-jit-index"));
        Ok(())
    }

    #[test]
    fn flags_absolute_home_path() -> Result<()> {
        let dir = TempDir::new()?;
        write_agents_md(dir.path(), "# Project\n\nSee /Users/micro/code here.\n");
        let scanner = AgentsMdScanner::new();
        let issues = scanner.scan(&dir.path().to_string_lossy())?;
        assert!(issues
            .iter()
            .any(|i| i.rule == "agents-md-no-absolute-paths" && i.severity == "warning"));
        Ok(())
    }

    #[test]
    fn flags_absolute_linux_home_path() -> Result<()> {
        let dir = TempDir::new()?;
        write_agents_md(dir.path(), "# Project\n\nSee /home/dev/code here.\n");
        let scanner = AgentsMdScanner::new();
        let issues = scanner.scan(&dir.path().to_string_lossy())?;
        assert!(issues
            .iter()
            .any(|i| i.rule == "agents-md-no-absolute-paths"));
        Ok(())
    }

    #[test]
    fn flags_ai_attribution() -> Result<()> {
        let dir = TempDir::new()?;
        write_agents_md(
            dir.path(),
            "# Project\n\nCo-Authored-By: Devin <noreply@example.com>\n",
        );
        let scanner = AgentsMdScanner::new();
        let issues = scanner.scan(&dir.path().to_string_lossy())?;
        assert!(issues
            .iter()
            .any(|i| i.rule == "agents-md-no-ai-attribution" && i.severity == "error"));
        Ok(())
    }

    #[test]
    fn flags_generated_by_ai_attribution() -> Result<()> {
        let dir = TempDir::new()?;
        write_agents_md(dir.path(), "# Project\n\nGenerated by AI\n");
        let scanner = AgentsMdScanner::new();
        let issues = scanner.scan(&dir.path().to_string_lossy())?;
        assert!(issues
            .iter()
            .any(|i| i.rule == "agents-md-no-ai-attribution"));
        Ok(())
    }

    #[test]
    fn flags_missing_child_chain() -> Result<()> {
        let dir = TempDir::new()?;
        write_agents_md(
            dir.path(),
            "# Project\n\nSee [sub](./sub/AGENTS.md) for details.\n",
        );
        let scanner = AgentsMdScanner::new();
        let issues = scanner.scan(&dir.path().to_string_lossy())?;
        assert!(issues
            .iter()
            .any(|i| i.rule == "agents-md-child-chain" && i.severity == "warning"));
        Ok(())
    }

    #[test]
    fn child_chain_present_passes() -> Result<()> {
        let dir = TempDir::new()?;
        write_agents_md(
            dir.path(),
            "# Project\n\nSee [sub](./sub/AGENTS.md) for details.\n",
        );
        std::fs::create_dir_all(dir.path().join("sub")).unwrap();
        std::fs::write(dir.path().join("sub").join("AGENTS.md"), "# Sub\n").unwrap();
        let scanner = AgentsMdScanner::new();
        let issues = scanner.scan(&dir.path().to_string_lossy())?;
        assert!(!issues.iter().any(|i| i.rule == "agents-md-child-chain"));
        Ok(())
    }

    #[test]
    fn child_chain_disabled() -> Result<()> {
        let dir = TempDir::new()?;
        write_agents_md(
            dir.path(),
            "# Project\n\nSee [sub](./sub/AGENTS.md) for details.\n",
        );
        let scanner = AgentsMdScanner::with_config(false, false, false, Vec::new());
        let issues = scanner.scan(&dir.path().to_string_lossy())?;
        assert!(!issues.iter().any(|i| i.rule == "agents-md-child-chain"));
        Ok(())
    }

    #[test]
    fn claude_md_is_scanned() -> Result<()> {
        let dir = TempDir::new()?;
        std::fs::write(
            dir.path().join("CLAUDE.md"),
            "# Project\n\nGenerated by Devin\n",
        )
        .unwrap();
        let scanner = AgentsMdScanner::new();
        let issues = scanner.scan(&dir.path().to_string_lossy())?;
        assert!(issues
            .iter()
            .any(|i| i.rule == "agents-md-no-ai-attribution" && i.file == "CLAUDE.md"));
        Ok(())
    }

    #[test]
    fn empty_agents_md_no_issues() -> Result<()> {
        let dir = TempDir::new()?;
        write_agents_md(dir.path(), "");
        let scanner = AgentsMdScanner::new();
        assert!(scanner.scan(&dir.path().to_string_lossy())?.is_empty());
        Ok(())
    }

    #[test]
    fn no_agents_md_silent() -> Result<()> {
        let dir = TempDir::new()?;
        std::fs::write(dir.path().join("README.md"), "# Readme\n").unwrap();
        let scanner = AgentsMdScanner::new();
        assert!(scanner.scan(&dir.path().to_string_lossy())?.is_empty());
        Ok(())
    }

    #[test]
    fn has_section_detects_heading() {
        assert!(has_section("# usage protocol\n", "usage protocol"));
        assert!(has_section("## jit index\n", "jit index"));
        assert!(!has_section(
            "usage protocol without heading\n",
            "usage protocol"
        ));
    }

    #[test]
    fn has_absolute_home_path_detects() {
        assert!(has_absolute_home_path("see /Users/micro/code"));
        assert!(has_absolute_home_path("see /home/dev/code"));
        assert!(!has_absolute_home_path("see ./relative/path"));
    }

    #[test]
    fn extract_child_agents_refs_finds_markdown_link() {
        let refs = extract_child_agents_refs("See [sub](./sub/AGENTS.md) for details.");
        assert!(refs.iter().any(|r| r.contains("AGENTS.md")));
    }
}
