//! Path hygiene scanner — validates all committed text files for path
//! hygiene: no absolute home paths, no AI attribution boilerplate, no AI
//! signature comments in source headers. Enforces three rules:
//!
//! 1. **no-absolute-home-paths** — no committed file should contain
//!    `/Users/<username>/` or `/home/<username>/` paths (warning).
//!    Exempt files (`.envrc`, `.gitignore`, `*.env`) that legitimately
//!    reference home paths are skipped.
//! 2. **no-ai-attribution** — no committed file should contain AI tool
//!    attribution boilerplate like "Generated with [Devin]" or
//!    "Co-Authored-By: Devin" (error).
//! 3. **no-ai-signature-comments** — no committed file should contain
//!    AI tool signature comments in source code headers (error).
//!
//! This scanner is cross-cutting (all text files) and uses the
//! centralized exclusion list to skip `node_modules/`, `target/`, etc.

use crate::scanners::ScannerIssue;
use crate::utils::{build_exclusions, is_excluded_rel, matches_pattern, walk_project, Result};
use std::path::Path;
use tracing::debug;

/// Default exempt file patterns for the `no-absolute-home-paths` rule.
pub const DEFAULT_EXEMPT_FILES: &[&str] = &[".envrc", ".gitignore", "*.env", "*.env.*"];

/// Default AI-attribution patterns for the `no-ai-attribution` rule.
pub const DEFAULT_AI_ATTRIBUTION_PATTERNS: &[&str] = &[
    "Generated with [Devin]",
    "Co-Authored-By: Devin",
    "Generated by AI",
    "Generated by Devin",
];

/// Default AI-signature comment patterns for the `no-ai-signature-comments`
/// rule.
pub const DEFAULT_AI_SIGNATURE_PATTERNS: &[&str] = &[
    "AI-generated",
    "Generated by Claude",
    "Generated by Copilot",
    "Generated by ChatGPT",
    "// AI:",
    "// AI-Generated:",
];

/// Text file extensions scanned by this scanner. Non-text files (binary,
/// images, etc.) are skipped.
const TEXT_EXTENSIONS: &[&str] = &[
    "rs",
    "py",
    "js",
    "ts",
    "tsx",
    "jsx",
    "go",
    "java",
    "kt",
    "swift",
    "c",
    "cpp",
    "h",
    "hpp",
    "rb",
    "php",
    "scala",
    "sh",
    "bash",
    "zsh",
    "fish",
    "ps1",
    "bat",
    "cmd",
    "nix",
    "lua",
    "r",
    "sql",
    "proto",
    "thrift",
    "graphql",
    "gql",
    "vue",
    "svelte",
    "html",
    "css",
    "scss",
    "sass",
    "less",
    "xml",
    "yaml",
    "yml",
    "toml",
    "json",
    "json5",
    "jsonc",
    "ini",
    "cfg",
    "conf",
    "env",
    "properties",
    "gradle",
    "md",
    "rst",
    "txt",
    "dockerfile",
    "containerfile",
    "gemspec",
    "makefile",
    "mk",
    "cmake",
    "mod",
    "sum",
    "work",
    "lock",
    "tf",
    "tfvars",
    "hcl",
    "ninja",
    "csv",
    "tsv",
    "log",
    "diff",
    "patch",
];

/// Special filenames (no extension) treated as text files.
const TEXT_SPECIAL_NAMES: &[&str] = &[
    "Dockerfile",
    "Containerfile",
    "Makefile",
    "Justfile",
    "justfile",
    "Rakefile",
    "Gemfile",
    "LICENSE",
    "LICENSE.txt",
    "COPYING",
    "AUTHORS",
    "CHANGELOG",
    "NOTICE",
    ".envrc",
    ".gitignore",
    ".gitattributes",
    ".editorconfig",
    ".npmrc",
    ".nvmrc",
    ".python-version",
    ".ruby-version",
    ".tool-versions",
];

/// Maximum file size (in bytes) to scan. Files larger than this are skipped
/// to avoid reading huge generated/minified files.
const MAX_FILE_SIZE: u64 = 512 * 1024;

pub struct PathHygieneScanner {
    check_absolute_home: bool,
    check_ai_attribution: bool,
    check_ai_signature: bool,
    exempt_files: Vec<String>,
    attribution_patterns: Vec<String>,
    signature_patterns: Vec<String>,
    excluded: Vec<String>,
}

impl PathHygieneScanner {
    pub fn new() -> Self {
        Self {
            check_absolute_home: true,
            check_ai_attribution: true,
            check_ai_signature: true,
            exempt_files: DEFAULT_EXEMPT_FILES.iter().map(|s| s.to_string()).collect(),
            attribution_patterns: DEFAULT_AI_ATTRIBUTION_PATTERNS
                .iter()
                .map(|s| s.to_string())
                .collect(),
            signature_patterns: DEFAULT_AI_SIGNATURE_PATTERNS
                .iter()
                .map(|s| s.to_string())
                .collect(),
            excluded: build_exclusions(&[], false),
        }
    }

    pub fn with_config(
        check_absolute_home: bool,
        check_ai_attribution: bool,
        check_ai_signature: bool,
        exempt_files: Vec<String>,
        attribution_patterns: Vec<String>,
        signature_patterns: Vec<String>,
    ) -> Self {
        Self {
            check_absolute_home,
            check_ai_attribution,
            check_ai_signature,
            exempt_files,
            attribution_patterns,
            signature_patterns,
            excluded: build_exclusions(&[], false),
        }
    }

    pub fn with_exclusions(
        check_absolute_home: bool,
        check_ai_attribution: bool,
        check_ai_signature: bool,
        exempt_files: Vec<String>,
        attribution_patterns: Vec<String>,
        signature_patterns: Vec<String>,
        excluded: Vec<String>,
    ) -> Self {
        Self {
            check_absolute_home,
            check_ai_attribution,
            check_ai_signature,
            exempt_files,
            attribution_patterns,
            signature_patterns,
            excluded,
        }
    }

    /// Scan a project root for text files and validate path hygiene.
    pub fn scan(&self, project_path: &str) -> Result<Vec<ScannerIssue>> {
        let root = Path::new(project_path);
        let mut issues = Vec::new();

        for entry in walk_project(root, &self.excluded, 6).filter(|e| e.file_type().is_file()) {
            let path = entry.path();
            let rel = path
                .strip_prefix(root)
                .unwrap_or(path)
                .to_string_lossy()
                .to_string();
            if is_excluded_rel(&rel, &self.excluded) {
                continue;
            }
            if !self.is_text_file(path) {
                continue;
            }
            if let Ok(metadata) = std::fs::metadata(path) {
                if metadata.len() > MAX_FILE_SIZE {
                    debug!(
                        "path_hygiene: skipping {} ({} bytes, over limit)",
                        rel,
                        metadata.len()
                    );
                    continue;
                }
            }
            debug!("path_hygiene: scanning {}", rel);
            issues.extend(self.scan_file(path, &rel));
        }

        Ok(issues)
    }

    fn is_text_file(&self, path: &Path) -> bool {
        let name = path.file_name().unwrap_or_default().to_string_lossy();
        if TEXT_SPECIAL_NAMES.contains(&name.as_ref()) {
            return true;
        }
        if let Some(ext) = path.extension() {
            let ext = ext.to_string_lossy().to_lowercase();
            if TEXT_EXTENSIONS.contains(&ext.as_str()) {
                return true;
            }
        }
        false
    }

    fn is_exempt(&self, name: &str) -> bool {
        for pat in &self.exempt_files {
            if matches_pattern(name, pat) {
                return true;
            }
        }
        false
    }

    fn scan_file(&self, path: &Path, rel: &str) -> Vec<ScannerIssue> {
        let mut issues = Vec::new();
        let Ok(content) = std::fs::read_to_string(path) else {
            return issues;
        };
        let name = path.file_name().unwrap_or_default().to_string_lossy();
        let is_exempt_file = self.is_exempt(&name);

        for (i, line) in content.lines().enumerate() {
            if self.check_absolute_home && !is_exempt_file && has_absolute_home_path(line) {
                issues.push(
                    ScannerIssue::new(
                        "no-absolute-home-paths",
                        "warning",
                        rel,
                        format!("absolute home path found: {}", line.trim()),
                    )
                    .at_line(i + 1),
                );
            }
            if self.check_ai_attribution {
                for pat in &self.attribution_patterns {
                    if line.contains(pat) {
                        issues.push(
                            ScannerIssue::new(
                                "no-ai-attribution",
                                "error",
                                rel,
                                format!("AI tool attribution found: {}", pat),
                            )
                            .at_line(i + 1),
                        );
                    }
                }
            }
            if self.check_ai_signature {
                for pat in &self.signature_patterns {
                    if line.contains(pat) {
                        issues.push(
                            ScannerIssue::new(
                                "no-ai-signature-comments",
                                "error",
                                rel,
                                format!("AI signature comment found: {}", pat),
                            )
                            .at_line(i + 1),
                        );
                    }
                }
            }
        }

        issues
    }
}

impl Default for PathHygieneScanner {
    fn default() -> Self {
        Self::new()
    }
}

/// Detect absolute home paths: `/Users/<name>/` or `/home/<name>/`.
fn has_absolute_home_path(line: &str) -> bool {
    (line.contains("/Users/") && line.contains("/"))
        || (line.contains("/home/") && line.contains("/"))
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn clean_file_no_issues() -> Result<()> {
        let dir = TempDir::new()?;
        std::fs::write(dir.path().join("main.rs"), "fn main() {}\n")?;
        let scanner = PathHygieneScanner::new();
        assert!(scanner.scan(&dir.path().to_string_lossy())?.is_empty());
        Ok(())
    }

    #[test]
    fn flags_absolute_home_path() -> Result<()> {
        let dir = TempDir::new()?;
        std::fs::write(
            dir.path().join("main.rs"),
            "let p = \"/Users/micro/code\";\n",
        )?;
        let scanner = PathHygieneScanner::new();
        let issues = scanner.scan(&dir.path().to_string_lossy())?;
        assert!(issues
            .iter()
            .any(|i| i.rule == "no-absolute-home-paths" && i.severity == "warning"));
        Ok(())
    }

    #[test]
    fn flags_linux_home_path() -> Result<()> {
        let dir = TempDir::new()?;
        std::fs::write(dir.path().join("main.py"), "path = \"/home/dev/code\"\n")?;
        let scanner = PathHygieneScanner::new();
        let issues = scanner.scan(&dir.path().to_string_lossy())?;
        assert!(issues.iter().any(|i| i.rule == "no-absolute-home-paths"));
        Ok(())
    }

    #[test]
    fn exempt_files_not_flagged_for_paths() -> Result<()> {
        let dir = TempDir::new()?;
        std::fs::write(
            dir.path().join(".envrc"),
            "export PATH=/Users/micro/bin:$PATH\n",
        )?;
        let scanner = PathHygieneScanner::new();
        let issues = scanner.scan(&dir.path().to_string_lossy())?;
        assert!(!issues
            .iter()
            .any(|i| i.rule == "no-absolute-home-paths" && i.file == ".envrc"));
        Ok(())
    }

    #[test]
    fn flags_ai_attribution() -> Result<()> {
        let dir = TempDir::new()?;
        std::fs::write(
            dir.path().join("README.md"),
            "# Project\n\nCo-Authored-By: Devin <noreply@example.com>\n",
        )?;
        let scanner = PathHygieneScanner::new();
        let issues = scanner.scan(&dir.path().to_string_lossy())?;
        assert!(issues
            .iter()
            .any(|i| i.rule == "no-ai-attribution" && i.severity == "error"));
        Ok(())
    }

    #[test]
    fn flags_generated_with_devin() -> Result<()> {
        let dir = TempDir::new()?;
        std::fs::write(
            dir.path().join("README.md"),
            "# Project\n\nGenerated with [Devin]\n",
        )?;
        let scanner = PathHygieneScanner::new();
        let issues = scanner.scan(&dir.path().to_string_lossy())?;
        assert!(issues.iter().any(|i| i.rule == "no-ai-attribution"));
        Ok(())
    }

    #[test]
    fn flags_ai_signature_comment() -> Result<()> {
        let dir = TempDir::new()?;
        std::fs::write(
            dir.path().join("main.rs"),
            "// AI-generated code\nfn main() {}\n",
        )?;
        let scanner = PathHygieneScanner::new();
        let issues = scanner.scan(&dir.path().to_string_lossy())?;
        assert!(issues
            .iter()
            .any(|i| i.rule == "no-ai-signature-comments" && i.severity == "error"));
        Ok(())
    }

    #[test]
    fn flags_generated_by_claude_signature() -> Result<()> {
        let dir = TempDir::new()?;
        std::fs::write(
            dir.path().join("main.py"),
            "# Generated by Claude\nprint('hi')\n",
        )?;
        let scanner = PathHygieneScanner::new();
        let issues = scanner.scan(&dir.path().to_string_lossy())?;
        assert!(issues.iter().any(|i| i.rule == "no-ai-signature-comments"));
        Ok(())
    }

    #[test]
    fn config_can_disable_checks() -> Result<()> {
        let dir = TempDir::new()?;
        std::fs::write(
            dir.path().join("main.rs"),
            "// AI-generated\nlet p = \"/Users/micro/code\";\nCo-Authored-By: Devin\n",
        )?;
        let scanner = PathHygieneScanner::with_config(
            false,
            false,
            false,
            Vec::new(),
            Vec::new(),
            Vec::new(),
        );
        assert!(scanner.scan(&dir.path().to_string_lossy())?.is_empty());
        Ok(())
    }

    #[test]
    fn empty_file_no_issues() -> Result<()> {
        let dir = TempDir::new()?;
        std::fs::write(dir.path().join("empty.rs"), "")?;
        let scanner = PathHygieneScanner::new();
        assert!(scanner.scan(&dir.path().to_string_lossy())?.is_empty());
        Ok(())
    }

    #[test]
    fn no_text_files_silent() -> Result<()> {
        let dir = TempDir::new()?;
        std::fs::write(dir.path().join("image.png"), b"\x89PNG\r\n\x1a\n")?;
        let scanner = PathHygieneScanner::new();
        assert!(scanner.scan(&dir.path().to_string_lossy())?.is_empty());
        Ok(())
    }

    #[test]
    fn dockerfile_scanned() -> Result<()> {
        let dir = TempDir::new()?;
        std::fs::write(
            dir.path().join("Dockerfile"),
            "# Generated by Claude\nFROM node:20\n",
        )?;
        let scanner = PathHygieneScanner::new();
        let issues = scanner.scan(&dir.path().to_string_lossy())?;
        assert!(issues
            .iter()
            .any(|i| i.rule == "no-ai-signature-comments" && i.file == "Dockerfile"));
        Ok(())
    }

    #[test]
    fn skips_excluded_dirs() -> Result<()> {
        let dir = TempDir::new()?;
        std::fs::create_dir_all(dir.path().join("target"))?;
        std::fs::write(
            dir.path().join("target").join("build.rs"),
            "// AI-generated\nfn main() {}\n",
        )?;
        let scanner = PathHygieneScanner::new();
        let issues = scanner.scan(&dir.path().to_string_lossy())?;
        assert!(!issues
            .iter()
            .any(|i| i.rule == "no-ai-signature-comments" && i.file.contains("target/")));
        Ok(())
    }

    #[test]
    fn custom_attribution_patterns() -> Result<()> {
        let dir = TempDir::new()?;
        std::fs::write(dir.path().join("README.md"), "# Project\n\nMade by BotX\n")?;
        let scanner = PathHygieneScanner::with_config(
            true,
            true,
            true,
            Vec::new(),
            vec!["Made by BotX".to_string()],
            Vec::new(),
        );
        let issues = scanner.scan(&dir.path().to_string_lossy())?;
        assert!(issues
            .iter()
            .any(|i| i.rule == "no-ai-attribution" && i.message.contains("BotX")));
        Ok(())
    }

    #[test]
    fn has_absolute_home_path_detects() {
        assert!(has_absolute_home_path("let p = \"/Users/micro/code\";"));
        assert!(has_absolute_home_path("path = \"/home/dev/code\""));
        assert!(!has_absolute_home_path("let p = \"./relative/path\";"));
    }

    #[test]
    fn is_text_file_detects_extensions() {
        let scanner = PathHygieneScanner::new();
        assert!(scanner.is_text_file(Path::new("main.rs")));
        assert!(scanner.is_text_file(Path::new("config.yaml")));
        assert!(scanner.is_text_file(Path::new("Dockerfile")));
        assert!(!scanner.is_text_file(Path::new("image.png")));
        assert!(!scanner.is_text_file(Path::new("binary")));
    }
}
