// project-lint hook extension for pi
// Auto-generated by `project-lint install-hook --agent pi`
//
// This extension bridges pi's in-process tool_call event to project-lint's
// stdin/stdout hook protocol. It sends the event as a Claude Code-compatible
// JSON payload to `project-lint hook --source claude` and applies any
// modified input returned by project-lint back to the tool call.
//
// To install globally instead of project-local, copy this file to:
//   ~/.pi/agent/extensions/project-lint-hook.ts

import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { spawn } from "node:child_process";
import { existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

// Resolve the project-lint binary at runtime without embedding any
// absolute path. Checks dev builds relative to known project-root env
// vars and the extension's own location, then falls back to PATH.
function resolveProjectLintBin(): string {
  // Explicit override
  if (process.env.PROJECT_LINT_BIN) return process.env.PROJECT_LINT_BIN;

  // Check known project-root env vars (per official docs as of 2026-08)
  const rootVars = [
    "CLAUDE_PROJECT_DIR",
    "CURSOR_PROJECT_DIR",
    "DEVIN_PROJECT_DIR",
  ];
  for (const v of rootVars) {
    const root = process.env[v];
    if (!root) continue;
    for (const profile of ["release", "debug"]) {
      const candidate = join(root, "target", profile, "project-lint");
      if (existsSync(candidate)) return candidate;
    }
  }

  // Walk up from this extension's directory to find target/{release,debug}/
  // Extension lives at <project_root>/.pi/extensions/project-lint-hook.ts
  let dir = dirname(fileURLToPath(import.meta.url));
  for (let i = 0; i < 10; i++) {
    for (const profile of ["release", "debug"]) {
      const candidate = join(dir, "target", profile, "project-lint");
      if (existsSync(candidate)) return candidate;
    }
    const parent = dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }

  // Fallback: rely on PATH lookup via spawn
  return "project-lint";
}

const PROJECT_LINT_BIN = resolveProjectLintBin();

export default function (pi: ExtensionAPI) {
  pi.on("tool_call", async (event, _ctx) => {
    // Convert pi's tool_call event to Claude Code hook format
    const hookPayload = JSON.stringify({
      hook_event_name: "PreToolUse",
      tool_name: event.toolName,
      tool_input: event.input,
    });

    return new Promise((resolve) => {
      const child = spawn(PROJECT_LINT_BIN, ["hook", "--source", "claude"], {
        stdio: ["pipe", "pipe", "pipe"],
      });

      let stdout = "";
      let stderr = "";

      child.stdout.on("data", (data: Buffer) => { stdout += data.toString(); });
      child.stderr.on("data", (data: Buffer) => { stderr += data.toString(); });

      child.on("close", (code: number | null) => {
        try {
          if (stdout.trim()) {
            const response = JSON.parse(stdout);

            // Apply modified input to the tool call
            if (response.hookSpecificOutput?.updatedInput) {
              const updated = response.hookSpecificOutput.updatedInput;
              for (const [key, value] of Object.entries(updated)) {
                (event.input as Record<string, unknown>)[key] = value;
              }
            }

            // Block if project-lint denied the action
            if (response.continue === false) {
              resolve({
                block: true,
                reason: response.stopReason || "Blocked by project-lint",
              });
              return;
            }
          }
        } catch {
          // Ignore JSON parse errors — allow the tool call through
        }

        // Exit code 2 means block in Claude Code hook protocol
        if (code === 2) {
          resolve({
            block: true,
            reason: stderr.trim() || "Blocked by project-lint",
          });
          return;
        }

        resolve(undefined);
      });

      child.on("error", () => {
        // If project-lint binary is not found, silently allow the tool call
        resolve(undefined);
      });

      child.stdin.write(hookPayload);
      child.stdin.end();
    });
  });
}
